pipeline {
    agent any

    environment {
        APP_DIR = "04-docker"
        VENV_DIR = "j-venv"
        IMAGE_NAME = "zeeshanaslam1984/zshan-jenkins-docker-flask-app"
    }

    stages {
        stage('Setup & Install') {
            steps {
                sh '''
                    echo "📦 Setting up virtual environment..."
                    python3 -m venv ${VENV_DIR}
                    . ${VENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r ${APP_DIR}/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    . ${VENV_DIR}/bin/activate
                    echo "Running tests in ${APP_DIR} only..."
                    pytest ${APP_DIR}
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'docker-creds',
                        usernameVariable: 'USERNAME',
                        passwordVariable: 'PASSWORD'
                    )]) {
                        sh 'echo "${PASSWORD}" | docker login -u "${USERNAME}" --password-stdin'
                        echo '✅ Login successful'
                    }
                }
            }
        }

        stage('Build & Push Docker Image') {
            steps {
                sh '''
                    echo "🐳 Building Docker image..."
                    docker build -t ${IMAGE_NAME}:latest ${APP_DIR}

                    echo "📤 Pushing Docker image..."
                    docker push ${IMAGE_NAME}:latest
                '''
            }
        }
    }

    post {
        always {
            echo '🧹 Cleaning up virtual environment...'
            sh 'rm -rf ${VENV_DIR}'
        }
    }
}
